### ISSUE TITLE
code questions

### ISSUE THREAD

**Issue by yanglong0228** [Chan-Sun/IFSDD#6]
2024-04-06 23:10:51,681 - mmfewshot - INFO - Set random seed to 42, deterministic: Fals

2024-04-06 23:10:51,941 - mmfewshot - INFO - initialize ResNet with init_cfg {'type': 'Pretrained', 'checkpoint': 'torchvision://resnet50'}
2024-04-06 23:10:51,942 - mmcv - INFO - load model from: torchvision://resnet50
2024-04-06 23:10:51,942 - mmcv - INFO - load checkpoint from torchvision path: torchvision://resnet50
2024-04-06 23:10:52,038 - mmcv - WARNING - The model and loaded state dict do not match exactly

unexpected key in source state_dict: fc.weight, fc.bias

2024-04-06 23:10:52,062 - mmfewshot - INFO - initialize FPN with init_cfg {'type': 'Xavier', 'layer': 'Conv2d', 'distribution': 'uniform'}
2024-04-06 23:10:52,079 - mmfewshot - INFO - initialize RPNHead with init_cfg {'type': 'Normal', 'layer': 'Conv2d', 'std': 0.01}
2024-04-06 23:10:52,084 - mmfewshot - INFO - initialize Shared2FCBBoxHead with init_cfg [{'type': 'Normal', 'std': 0.01, 'override': {'name': 'fc_cls'}}, {'type': 'Normal', 'std': 0.001, 'override': {'name': 'fc_reg'}}, {'type': 'Xavier', 'distribution': 'uniform', 'override': [{'name': 'shared_fcs'}, {'name': 'cls_fcs'}, {'name': 'reg_fcs'}]}]
Traceback (most recent call last):
  File "/home/lenovo/anaconda3/envs/yl-torch/lib/python3.8/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/home/lenovo/桌面/DKAN-master/dkan/dataset.py", line 33, in __init__
    self.SPLIT = SPLIT[defect_name]
KeyError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lenovo/桌面/DKAN-master/train.py", line 190, in <module>
    main()
  File "/home/lenovo/桌面/DKAN-master/train.py", line 160, in main
    build_dataset(
  File "/home/lenovo/桌面/DKAN-master/packages/mmfewshot-0.1.0/mmfewshot/detection/datasets/builder.py", line 106, in build_dataset
    main_dataset = build_dataset(cfg['dataset'], default_args)
  File "/home/lenovo/桌面/DKAN-master/packages/mmfewshot-0.1.0/mmfewshot/detection/datasets/builder.py", line 126, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/home/lenovo/anaconda3/envs/yl-torch/lib/python3.8/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
KeyError: 'FewShotDefectDataset: None
学长这是报错的信息。那三个库mmdetection mmfewshot mmrazor 都有按要求安装。版本也都检查过，mmcv-full是1.4.6的。运行就是报这个error

**Comment by Chan-Sun** [comment]
Hi, 代码我整体过了一遍，有一些键值的问题改了一下，在我自己的新机器上跑成功了。

你可以重新下载整个项目，然后根据更新后的README来跑代码。

如果有新的问题欢迎在这个issue下面再提出。

**Comment by yanglong0228** [comment]
学长！我有下载了
1、数据集里的images这块有train和validation&nbsp; .xml格式的标签，但是和annotations里的test.json、trainval.json没有对应起来，该怎么去解决
2、针对上边，我直接运行该代码后有报出以下错误：

麻烦您可以给解惑下吗？真诚的感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Chan-Sun/IFSDD"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月10日(星期三) 上午9:57
***@***.***&gt;;
主题:&nbsp;Re: [Chan-Sun/IFSDD] code questions (Issue #6)





 
Hi, 代码我整体过了一遍，有一些键值的问题改了一下，在我自己的新机器上跑成功了。
 
你可以重新下载整个项目，然后根据更新后的README来跑代码。
 
如果有新的问题欢迎在这个issue下面再提出。

**Comment by Chan-Sun** [comment]
1. github里面提供的train-val split是我自己分的，数据分割的[代码](https://github.com/Chan-Sun/IFSDD/blob/main/dataset/utils/datasplit.py)也提供了。因为数据整体是同分布的，所以结果应该差不多，用哪个都可以。但是要保证和对比方法用的是同一个train-val split
2. 报错信息我没看到。

**Comment by yanglong0228** [comment]
这个微调训练后的权重文件进行测试的话，测试结果是一个.pickle结尾的文件。针对可视化这块有以下两个问题


（1）但是对于可视化的红色标框图的话，是运行utils包边的analysis.py文件还是analyze_results.py文件呀？
我跑analyze_results.py 文件，报了keyerror:'fewshotdefectdataset is not in the dataset registry .没有被注册，这个错误
（2）utils包下的collect_results.py、 confusiom_matrix.py、 initialize&gt;bbox_head.py、 post_analisis_iklf.py 这四个python文件分别是分析什么结果的呀？


期待收到学长的回复！真诚感谢





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Chan-Sun/IFSDD"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月21日(星期天) 晚上10:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Chan-Sun/IFSDD] code questions (Issue #6)





 
Closed #6 as completed.

**Comment by yanglong0228** [comment]
这个微调训练后的权重文件进行测试的话，测试结果是一个.pickle结尾的文件。针对可视化这块有以下两个问题


（1）但是对于可视化的红色标框图的话，是运行utils包边的analysis.py文件还是analyze_results.py文件呀？
我跑analyze_results.py 文件，报了keyerror:'fewshotdefectdataset is not in the dataset registry .没有被注册，这个错误



（2）utils包下的collect_results.py、 confusiom_matrix.py、 initialize&gt;bbox_head.py、 post_analisis_iklf.py 这四个python文件分别是分析什么结果的呀？


期待收到学长的回复！真诚感谢





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Chan-Sun/IFSDD"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月10日(星期三) 上午9:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Chan-Sun/IFSDD] code questions (Issue #6)





 
Hi, 代码我整体过了一遍，有一些键值的问题改了一下，在我自己的新机器上跑成功了。
 
你可以重新下载整个项目，然后根据更新后的README来跑代码。
 
如果有新的问题欢迎在这个issue下面再提出。
